services:
  route-relay:
    image: laxsrbija/route-relay:latest
    ports:
      - "80:8080"
    volumes:
      - type: bind
        source: ./config.json
        target: /app/config.json
    restart: unless-stopped
